steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'LOCATION-docker.pkg.dev/PROJECT_ID/REPO_NAME/IMAGE_NAME:$SHORT_SHA', '.']

  # Step 2: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'LOCATION-docker.pkg.dev/PROJECT_ID/REPO_NAME/IMAGE_NAME:$SHORT_SHA']

  # Step 3: Deploy the image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - SERVICE_NAME
      - --image
      - 'LOCATION-docker.pkg.dev/PROJECT_ID/REPO_NAME/IMAGE_NAME:$SHORT_SHA'
      - --region
      - REGION
      - --platform
      - managed
